---

- name: Install Git
  dnf:
    name: git
    state: latest

- name: Install Mosh
  dnf:
    name: mosh
    state: latest

- name: Install libselinux-python
  dnf:
    name: libselinux-python
    state: latest
