---

- name: Install Emacs
  become_user: root
  yum:
    name: emacs-nox
    state: latest

- name: Get latest emacs config
  become: no
  git:
    repo: https://github.com/nvkv/emacs.d.git
    dest: ~/.emacs.d
