---

- name: Setup tmux on Fedora
  include: Fedora.yml
  when: ansible_distribution == "Fedora"

- name: Setup tmux on CentOS
  include: CentOS.yml
  when: ansible_distribution == "CentOS"

- name: Configure tmux for Linux
  become: no
  template:
    src: tmux-linux.conf
    dest: ~/.tmux.conf
  when: ansible_distribution != "MacOSX"
